<?php

namespace Database\Seeders;

use App\Models\Stagiaires;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StagiairesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('stagiaires')->insert([
            [
                'CEF' => '2004050600229',
                'Nom' => 'OUADI',
                'Prenom' => 'WISSAL',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2003082700323',
                'Nom' => 'GOTAR',
                'Prenom' => 'SALMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2003112800369',
                'Nom' => 'ZBIR',
                'Prenom' => 'IBRAHIM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2004051700208',
                'Nom' => 'MOSHIB',
                'Prenom' => 'MERIEME',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2005102900119',
                'Nom' => 'SENAJI',
                'Prenom' => 'HIBA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2004012600325',
                'Nom' => 'EL FATIMI',
                'Prenom' => 'AHLAM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2004110300266',
                'Nom' => 'EL MAARRI',
                'Prenom' => 'AYA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2002052800412',
                'Nom' => 'ABADA',
                'Prenom' => 'KAOUTAR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2005090500108',
                'Nom' => 'HASBI',
                'Prenom' => 'MERIEM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2003040800361',
                'Nom' => 'KHALCEFI',
                'Prenom' => 'ACHRAF',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2000071400489',
                'Nom' => 'ASSAFAR',
                'Prenom' => 'SOUKAINA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2001122800150',
                'Nom' => 'HAFCEF',
                'Prenom' => 'HAMZA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2002063000364',
                'Nom' => 'HAMMI',
                'Prenom' => 'SALMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2003071500390',
                'Nom' => 'IGUCEFER',
                'Prenom' => 'KHADIJA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2004083100238',
                'Nom' => 'MIMI',
                'Prenom' => 'SALMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2001091700407',
                'Nom' => 'EL IMRANY',
                'Prenom' => 'OUSSAMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2004060900215',
                'Nom' => 'HALLAOUI',
                'Prenom' => 'KHADIJA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2003061100348',
                'Nom' => 'CHRIFI',
                'Prenom' => 'WIAME',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],

            [
                'CEF' => '2003100200330',
                'Nom' => 'JARRAH',
                'Prenom' => 'SALWA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],

            [
                'CEF' => '2002120700337',
                'Nom' => 'NAJINE',
                'Prenom' => 'YASSINE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],

            [
                'CEF' => '2003070100472',
                'Nom' => 'HADDAJ',
                'Prenom' => 'MERYEM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],

            [
                'CEF' => '2003020100465',
                'Nom' => 'JCEFOUA',
                'Prenom' => 'AYA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],

            [
                'CEF' => '1997030800310',
                'Nom' => 'ELHARRAK',
                'Prenom' => 'OUMAIMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],

            [
                'CEF' => '2003122400163',
                'Nom' => 'ASSOULAIMANI',
                'Prenom' => 'ASMAA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2002012600415',
                'Nom' => 'AIT BLAL',
                'Prenom' => 'BADR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2003050300325',
                'Nom' => 'HOSSNI',
                'Prenom' => 'SOHAIB',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2002110300337',
                'Nom' => 'BAROTY',
                'Prenom' => 'OTHMANE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2003042600304',
                'Nom' => 'EL FEROUHY',
                'Prenom' => 'HIBA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2002092900366',
                'Nom' => 'ZEKKAR',
                'Prenom' => 'SALMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2005030900146',
                'Nom' => 'MOULOUA',
                'Prenom' => 'IKRAM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2002010200699',
                'Nom' => 'ABDEDDINE',
                'Prenom' => 'SALMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2004110600233',
                'Nom' => 'ZHAR',
                'Prenom' => 'MOHAMED',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2003071700344',
                'Nom' => 'MOUKRIM',
                'Prenom' => 'MARWA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2004110400264',
                'Nom' => 'ENNAJI',
                'Prenom' => 'SAFAE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2002071300388',
                'Nom' => 'HAMIOUI',
                'Prenom' => 'YOUSSEF',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2004122700204',
                'Nom' => 'KHAOUA',
                'Prenom' => 'NIZAR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2002032900362',
                'Nom' => 'LACHRAME',
                'Prenom' => 'FATIHA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2002112400105',
                'Nom' => 'MOUTAYAKINE',
                'Prenom' => 'EL MEHDI',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2002082200399',
                'Nom' => 'AMESJOUN',
                'Prenom' => 'IKRAM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2001041400304',
                'Nom' => 'MOUIHI',
                'Prenom' => 'ZINEB',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2004121000251',
                'Nom' => 'HANNANE',
                'Prenom' => 'AYA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2003100300311',
                'Nom' => 'ELKHAROUAY',
                'Prenom' => 'WISSAM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2004030300329',
                'Nom' => 'KANTI',
                'Prenom' => 'OMAR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2004111600193',
                'Nom' => 'JEMMANE',
                'Prenom' => 'DOHA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2003112900395',
                'Nom' => 'LARAIBI',
                'Prenom' => 'AYA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2003100200398',
                'Nom' => 'AIT BOUAAZZA',
                'Prenom' => 'INSAF',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2004042800360',
                'Nom' => 'MOUTAANI',
                'Prenom' => 'NAJLAA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2004062600359',
                'Nom' => 'SEHAKI',
                'Prenom' => 'AICHA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2004011300361',
                'Nom' => 'GHAZI',
                'Prenom' => 'ABDERRZZAK',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2004110300166',
                'Nom' => 'MOUCHAYAD',
                'Prenom' => 'HANANE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2003010400408',
                'Nom' => 'YABOURI',
                'Prenom' => 'MERIEM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2004020400342',
                'Nom' => 'ELFAHMY',
                'Prenom' => 'ZINEB',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2004020200331',
                'Nom' => 'MOUSSADAQ',
                'Prenom' => 'AYOUB',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2002100300375',
                'Nom' => 'TAWFIK',
                'Prenom' => 'OUMAIMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2003060600443',
                'Nom' => 'BOULASDAL',
                'Prenom' => 'IMANE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2002103000387',
                'Nom' => 'LABLALI',
                'Prenom' => 'ZAKARIA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2002010400383',
                'Nom' => 'SOUSSI',
                'Prenom' => 'ACHRAF',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2005100800235',
                'Nom' => 'DAYA',
                'Prenom' => 'DRISS',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2002111200441',
                'Nom' => 'TALIL',
                'Prenom' => 'WISSAL',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2005030300282',
                'Nom' => 'EL HALIMI',
                'Prenom' => 'KAWTAR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2004061700315',
                'Nom' => 'BAGHIR',
                'Prenom' => 'HAJAR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103'
            ],
            [
                'CEF' => '2002071100423',
                'Nom' => 'RABIH',
                'Prenom' => 'WAFAA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103',
            ],
            [
                'CEF' => '2001112500484',
                'Nom' => 'BARKAM',
                'Prenom' => 'AMINA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103',
            ],
            [
                'CEF' => '2004021700330',
                'Nom' => 'HIBOUR',
                'Prenom' => 'GHITA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103',
            ],
            [
                'CEF' => '2005081700194',
                'Nom' => 'MOUDRIK',
                'Prenom' => 'IKRAM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103',
            ],
            [
                'CEF' => '2005042100210',
                'Nom' => 'SAKHI',
                'Prenom' => 'IBTISSAM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103',
            ],
            [
                'CEF' => '2004051100305',
                'Nom' => 'BOUAYAD',
                'Prenom' => 'KENZA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103',
            ],
            [
                'CEF' => '2004022200376',
                'Nom' => 'BAZAD',
                'Prenom' => 'SALMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104',
            ],
            [
                'CEF' => '2003091500458',
                'Nom' => 'LAHLOU',
                'Prenom' => 'IMANE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104',
            ],
            [
                'CEF' => '2003102800349',
                'Nom' => 'LAHMAM',
                'Prenom' => 'AYA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104',
            ],
            [
                'CEF' => '2005022200266',
                'Nom' => 'ABDERRAZIQ',
                'Prenom' => 'SAFAA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104',
            ],
            [
                'CEF' => '2004011700351',
                'Nom' => 'OUASSOUFI',
                'Prenom' => 'LEILA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104',
            ],
            [
                'CEF' => '2003053100305',
                'Nom' => 'CHAOUKI',
                'Prenom' => 'HAJAR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104',
            ],
            [
                'CEF' => '1997093000178',
                'Nom' => 'BOUAZIZI',
                'Prenom' => 'YASMINE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2004022300363',
                'Nom' => 'LOTFI',
                'Prenom' => 'HASSAN',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104',
            ],
            [
                'CEF' => '1999052300347',
                'Nom' => 'ZOUGGAR',
                'Prenom' => 'JAWAD',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104',
            ],
            [
                'CEF' => '2004102700325',
                'Nom' => 'HASSA',
                'Prenom' => 'KHADIJA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104'
            ],
            [
                'CEF' => '2002121800417',
                'Nom' => 'CHOUIRDI',
                'Prenom' => 'ZAHIRA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104'
            ],
            [
                'CEF' => '2004021200372',
                'Nom' => 'BOUMAAZ',
                'Prenom' => 'OUMAIMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104'
            ],
            [
                'CEF' => '2004012800410',
                'Nom' => 'ADERBAZ',
                'Prenom' => 'YASSER',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104'
            ],
            [
                'CEF' => '2004073000236',
                'Nom' => 'BOUHLAL',
                'Prenom' => 'ABDESSAMAD',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104'
            ],
            [
                'CEF' => '2004072000435',
                'Nom' => 'TORKZI',
                'Prenom' => 'BAHAE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104'
            ],
            [
                'CEF' => '2004111100353',
                'Nom' => 'TAHA',
                'Prenom' => 'MARIEM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104'
            ],
            [
                'CEF' => '2002101500467',
                'Nom' => 'LAFRCEF',
                'Prenom' => 'NABILA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104'
            ],
            [
                'CEF' => '2004062800398',
                'Nom' => 'SOUMILE',
                'Prenom' => 'RHOFRANE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104'
            ],
            [
                'CEF' => '2003112000540',
                'Nom' => 'BENDAIF',
                'Prenom' => 'WAFAA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105'
            ],
            [
                'CEF' => '2001102800468',
                'Nom' => 'BENBOUJEMAA',
                'Prenom' => 'MOHAMED NOUR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105'
            ],
            [
                'CEF' => '2001102800469',
                'Nom' => 'BENBOUJEMAA',
                'Prenom' => 'MOHAMED AYMEN',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105'
            ],
            [
                'CEF' => '2003090900405',
                'Nom' => 'RAHMOUNE',
                'Prenom' => 'WALCEF',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105'
            ],
            [
                'CEF' => '2005102200216',
                'Nom' => 'HBAZI',
                'Prenom' => 'KHADIJA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105'
            ],
            [
                'CEF' => '2004101000351',
                'Nom' => 'BEN ZDIGUEN',
                'Prenom' => 'AYA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105'
            ],
            [
                'CEF' => '2004072700402',
                'Nom' => 'ZMIOUANE',
                'Prenom' => 'SAIF EDDINE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2004040900305',
                'Nom' => 'MAZOUL',
                'Prenom' => 'YASSINE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2003090200363',
                'Nom' => 'AZZY',
                'Prenom' => 'DOHA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2001051200482',
                'Nom' => 'EL HALBAOUI',
                'Prenom' => 'ZINEB',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2004070800241',
                'Nom' => 'GUEZRA',
                'Prenom' => 'IKRAM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2005030300283',
                'Nom' => 'MASBAH',
                'Prenom' => 'HIBA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2003042000259',
                'Nom' => 'EZZAAY',
                'Prenom' => 'MANAL',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2004060900327',
                'Nom' => 'HAIMOUD',
                'Prenom' => 'ASMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2004040300254',
                'Nom' => 'EL YOUBI',
                'Prenom' => 'HIBA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2002071600506',
                'Nom' => 'EL ABDAOUI',
                'Prenom' => 'ZINEB',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2006012500189',
                'Nom' => 'MAAROUF',
                'Prenom' => 'JANNAT',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2005010700262',
                'Nom' => 'LAGMIRI',
                'Prenom' => 'AYA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2004080100417',
                'Nom' => 'KASSITE',
                'Prenom' => 'DOUAA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2002111700366',
                'Nom' => 'KARIMI',
                'Prenom' => 'ABDELGHANI',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2002052700234',
                'Nom' => 'CHAABI',
                'Prenom' => 'ZIAD',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2005071600204',
                'Nom' => 'EL AOUNY',
                'Prenom' => 'IKHLAS',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2002070100595',
                'Nom' => 'TOURC',
                'Prenom' => 'LANA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2005080600106',
                'Nom' => 'HAIMOUDA',
                'Prenom' => 'AYA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2004060700283',
                'Nom' => 'EL KAHI',
                'Prenom' => 'DOUNIA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA101',
            ],
            [
                'CEF' => '2004010400292',
                'Nom' => 'DAMSIRI',
                'Prenom' => 'FATIMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2003080800457',
                'Nom' => 'JDOURI',
                'Prenom' => 'YAHYA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2004032500330',
                'Nom' => 'BAJOURI',
                'Prenom' => 'NOURA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2003080800387',
                'Nom' => 'MISBAH',
                'Prenom' => 'NOHA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2004062800387',
                'Nom' => 'SANAD',
                'Prenom' => 'HAJAR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2005080800193',
                'Nom' => 'FATHALLAH',
                'Prenom' => 'IKRAM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2003062200386',
                'Nom' => 'TAHIR',
                'Prenom' => 'CHAIMAA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2003041200352',
                'Nom' => 'ARRAMMAL',
                'Prenom' => 'YASSINE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA102',
            ],
            [
                'CEF' => '2004011600379',
                'Nom' => 'BENTIROU',
                'Prenom' => 'SALMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2004100200339',
                'Nom' => 'KOUAY',
                'Prenom' => 'OUMAIMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2004012100282',
                'Nom' => 'LAHRIZI',
                'Prenom' => 'DOUAA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2002112400424',
                'Nom' => 'EL JAHCEF',
                'Prenom' => 'NADIA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2003082100381',
                'Nom' => 'AMHOUCH',
                'Prenom' => 'FATIMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2001082400528',
                'Nom' => 'ABDAOUI',
                'Prenom' => 'YASSIR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2002071700493',
                'Nom' => 'FAKHAR',
                'Prenom' => 'NISRINE',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2003042000405',
                'Nom' => 'SETRE',
                'Prenom' => 'FATIMA ZAHRA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2003010200665',
                'Nom' => 'MOUMNY',
                'Prenom' => 'AYA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2001043000414',
                'Nom' => 'KHOMASSI',
                'Prenom' => 'MANAL',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA105',
            ],
            [
                'CEF' => '2002122300332',
                'Nom' => 'SAMMAHI',
                'Prenom' => 'KAWTAR',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA103',
            ],
            [
                'CEF' => '2003050300402',
                'Nom' => 'EL GHARMANI',
                'Prenom' => 'IKRAM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2001122100395',
                'Nom' => 'NOUIGA',
                'Prenom' => 'BRAHIM',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104',
            ],
            [
                'CEF' => '2002091800437',
                'Nom' => 'NOURI CHAFI',
                'Prenom' => 'DOUAA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2000113000448',
                'Nom' => 'EL GHARBAOUI',
                'Prenom' => 'ZAKARIEA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA104',
            ],
            [
                'CEF' => '2004080900307',
                'Nom' => 'FAWZI',
                'Prenom' => 'SALMA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],
            [
                'CEF' => '2003061600468',
                'Nom' => 'GHESSANI CEFRISSI',
                'Prenom' => 'GHITA',
                'Etudiant_Actif' => 'Oui',
                'Filiere' => 'GC_AA_T_1A-Assistant Administratif (1A)-2023',
                'Groupe' => 'AA106',
            ],

        ]);
    }
}
